#!/bin/sh

set -e

script/build

if test -e "./_site/index.html";then
  echo "It builds!"
  rm -Rf _site
else
  echo "The example site doesn't seem to build. "
  exit 1
fi

gem build Lavender-Scholar-Lite.gemspec
